api/urls.py
from django.urls import path 

from .import views

urlpatterns = [

    path('inventory/', views.ProductListApiView.as_view(), name='api_product_list'),
    path('inventory/<id>/', views.ProductDetailApiView.as_view()),
    path('search/', views.ProductSearchAPIView.as_view()),

]

inventory/urls.py
from django.urls import path 

from .import views

app_name = 'product'

urlpatterns = [

    path('inventory/', views.Product_List.as_view(), name='product_list'),
    path('inventory/<id>/', views.product_detail, name='product_detail' ),

]

kiratech/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls', namespace='inventory')),
    path('api/', include('api.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models

# Create your models here.

inventory/models.py
from django.db import models



class Supplier(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='2. Suppliers'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=15, unique=True)
    description = models.CharField(max_length=200)
    note = models.TextField(blank=False)
    image = models.ImageField(upload_to='product/images', blank=True)
    stock = models.IntegerField()
    availability = models.BooleanField(default=False)
    supplier = models.ForeignKey(Supplier, related_name='suppliers', on_delete=models.CASCADE)
 
    class Meta:
        verbose_name_plural='1. Products'

    def __str__(self):
        return self.name

    @property
    def supplier_name(self):
        return self.supplier.name

        

api/views.py
from rest_framework import generics
from rest_framework.views import APIView
from .serializers import ProductSerializer
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from inventory.models import Product
from rest_framework import filters

from api import serializers

class ProductListApiView(generics.ListAPIView):
    serializer_class = ProductSerializer

    def get_queryset(self):
        return Product.objects.all()

class ProductDetailApiView(APIView):
    def get(self, request, id):
        product = get_object_or_404(Product, id=id)
        serializers = ProductSerializer(product)
        return Response(serializers.data)

from django.db.models import Q
class ProductSearchAPIView(APIView):
    def post(self, resquest, format=None):
        data = self.request.data
        str = data['name']
        q = (Q(name__icontains=str))
        queryset = Product.objects.all()
        queryset = queryset.filter(q)
        serializer = ProductSerializer(queryset, many=True)
        return Response(serializer.data)


         

inventory/views.py
from django.shortcuts import render
from django.views import generic

from .models import Supplier, Product





class Product_List(generic.ListView):
    model = Product
    template_name = 'inventory/product_list.html'
    context_object_name = 'queryset'


def product_detail(request,id):
    product = Product.objects.get(pk=id)

    context = {'product': product,}
                
    return render(request,'inventory/product_detail.html',context)




    

templates/inventory/base.html
<!DOCTYPE html>

<html lang="en">

    {% include "inventory/head.html" %}

    <body>



    {% include "inventory/nav.html" %}



        {% block content %}
        
        {% endblock content %}





    {% include "inventory/footer.html" %}


    </body>
</html>

templates/inventory/footer.html
{% load static %}


        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->

templates/inventory/head.html
{% load static %}




<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %} " rel="stylesheet" />
</head>

templates/inventory/header.html
{% load static %}

templates/inventory/nav.html
{% load static %}



  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#!">Cars</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'product:product_list' %}">Home</a></li>
              
            </ul>
      
        </div>
    </div>
</nav>
<!-- Header-->

<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder"> Car Inventory </h1>
        </div>
    </div>
</header>

templates/inventory/product_detail.html
{% extends "inventory/base.html" %}

{% load static %}



{% block content %}



<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{product.image.url}}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">{{product.description}}</div>
                <h1 class="display-5 fw-bolder">{{product.name}}</h1>
                <div class="fs-5 mb-5">
                    <span>{{product.supplier}}</span>
                </div>
                <p class="lead">{{product.note}}</p>
                   
                {% if product.availability == True %}
                 Availability: <input type="checkbox" id="scales" name="scales" checked> <br>
                {% else %}
                Availability: <input type="checkbox" id="scales" name="scales"> <br>
                {% endif %}




                Stock: <b>{{product.stock}}</b> 

            </div>
        </div>
    </div>
</section>






{% endblock content %}

templates/inventory/product_list.html
{% extends "inventory/base.html" %}

{% load static %}



{% block content %}
  

        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                 {% for product in queryset  %}
            
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img style="width: 250px; height: 150px;" class="card-img-top" src="{{product.image.url}}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{product.name}}</h5>
                                    <!-- Product price-->
                                    {{product.supplier}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product:product_detail' product.pk %}">View</a></div>
                            </div>
                        </div>
                    </div>
       
                    {% endfor %}

                  
                </div>
            </div>
        </section>

{% endblock content %}